name: build python
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - python/**
jobs:
  push:
    name: "yolks:python_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '3.12'
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3          
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: sleepystew
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./python
          file: ./python/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sleepystew/yolks:python_${{ matrix.tag }}
